# Generated by Django 6.0 on 2025-12-23 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResearchSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.TextField()),
                ("status", models.CharField(default="PENDING", max_length=20)),
                ("trace_id", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="research.researchsession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResearchReasoning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reasoning", models.TextField()),
                (
                    "research",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="research.researchsession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResearchCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_tokens", models.IntegerField()),
                ("output_tokens", models.IntegerField()),
                ("total_cost", models.FloatField()),
                (
                    "research",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="research.researchsession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResearchSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary", models.TextField()),
                (
                    "research",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="research.researchsession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UploadedDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="uploads/")),
                ("extracted_text", models.TextField()),
                (
                    "research",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="research.researchsession",
                    ),
                ),
            ],
        ),
    ]
