# Generated by Django 6.0 on 2025-12-23 09:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="researchsession",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="uploadeddocument",
            name="uploaded_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="researchcost",
            name="input_tokens",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="researchcost",
            name="output_tokens",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="researchcost",
            name="total_cost",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="uploadeddocument",
            name="research",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="research.researchsession",
            ),
        ),
    ]
