# Generated by Django 6.0 on 2025-12-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0002_researchsession_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="researchreasoning",
            name="reasoning",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="researchsummary",
            name="summary",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="uploadeddocument",
            name="extracted_text",
            field=models.TextField(blank=True),
        ),
    ]
